version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=P@55w0rd!
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=users